POST http://localhost:3000/api/auth/verify
Content-Type: application/json
Authorization: Access eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJmdWxsTmFtZSI6IlRlc3QgTmFtZSIsImlhdCI6MTU2NzA4OTk0NiwiZXhwIjoxNTY3MDkwMjQ2fQ.-GjLilHGZsjp6_mKaE9fUZ6CQ0dH6qUGSLUTejOqF3A; Refresh eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE1NjcwODk5NDYsImV4cCI6MTU2NzY5NDc0Nn0.YITRiQg36F8wTiwBlYHVVtjGJv_GjbmjckzOvKMaHTE;

{}
