export default {
	'dashboard': 'fas fa-chart-line',
	'food': 'fas fa-utensils',
	'circle': 'far fa-circle',
	'recipes': 'fas fa-book-open',
	'recipe': 'fas fa-book-open',
	'calculator': 'fas fa-calculator',
	'chevronDown': 'fas fa-chevron-down',
	'trash': 'far fa-trash-alt',
	'arrowDoubleLeft': 'fas fa-angle-double-left',
	'info': 'fas fa-info-circle',
	'close': 'fas fa-times',
	'home': 'fas fa-home',
	'exercise': 'fas fa-running',
	'exercises': 'fas fa-running',
	'burger': 'fas fa-bars',
};
