APP_NAME: 'daisy-web-app_default'
PORT: 3000
BASE_URL: 'http://localhost:3000'
MONGO_URI: 'mongodb://localhost/daisy'
SENTRY_DSN: ''
RESPONSE_DELAY: 0
ACCESS_USERNAME: 'admin'
ACCESS_PASSWORD: 'admin'
