appName: 'daisy-web-app_default'
port: 3000
baseUrl: 'http://localhost:3000'

debug:
  responseDelay: 0

mongo:
  uri: 'mongodb://localhost/daisy'

sentry:
  dsn: ''

access:
  username: ''
  password: ''

firebase:
  apiKey: ''
  authDomain: ''
  databaseURL: ''
  projectId: ''
  storageBucket: ''
  messagingSenderId: ''
  appId: ''
