PORT: 3000
BASE_URL: 'http://localhost:3000'
MONGO_URI: 'mongodb://localhost/daisy'
SENTRY_DSN: ''

HTTP_ACCESS_USERNAME: ''
HTTP_ACCESS_PASSWORD: ''
AUTH_SECRET: 'someRandomThingsHere1234'
AUTH_SALT_ROUNDS: 10
ACCESS_TOKEN_EXPIRATION_IN_MINUTES: 10080
EMAIL_TOKEN_EXPIRATION_IN_MINUTES: 120
REGISTRATION_DISABLED: false

EMAIL_FROM_ADDRESS: 'no-reply@dev.daisy.com'
MAILGUN_API_KEY: ''
MAILGUN_DOMAIN: ''

RESPONSE_DELAY: 0
NO_CLIENT: false
CLEAN_UP_TEMP_FOLDER: true
