client:
  DEV_PORT: 3000
  API_BASE_URL: 'http://localhost:8080/api'
  DEFAULT_LAYOUT: 'LayoutSimple'
  DEFAULT_LOCALE: 'en-US'

server:
  ACCESS_PASSWORD: 'admin'
  ACCESS_USERNAME: 'admin'
  MONGO_URI: 'mongodb://localhost/daisy'
  RESPONSE_DELAY: 0
  PORT: 8080
