common:
  DEFAULT_LOCALE: 'en-US'

client:
  DEV_PORT: 3000
  API_BASE_URL: 'http://localhost:8080/api'
  DEFAULT_LAYOUT: 'LayoutSimple'

server:
  MONGO_URI: 'mongodb://admin:admin@localhost:27017/daisy'
  RESPONSE_DELAY: 0
  PORT: 8080
